2022-07-14 17:15:32,537 [INFO] - CbrApi:Started update for: XRate(840=>643): 1.0
2022-07-14 17:15:32,537 [DEBUG] - CbrApi:rate before: XRate(840=>643): 1.0
2022-07-14 17:15:34,323 [DEBUG] - CbrApi:response.encoding: windows-1251
2022-07-14 17:15:34,323 [DEBUG] - CbrApi:response.text: <?xml version="1.0" encoding="windows-1251"?><ValCurs Date="15.07.2022" name="Foreign Currency Market"><Valute ID="R01010"><NumCode>036</NumCode><CharCode>AUD</CharCode><Nominal>1</Nominal><Name>Австралийский доллар</Name><Value>39,3641</Value></Valute><Valute ID="R01020A"><NumCode>944</NumCode><CharCode>AZN</CharCode><Nominal>1</Nominal><Name>Азербайджанский манат</Name><Value>34,2687</Value></Valute><Valute ID="R01035"><NumCode>826</NumCode><CharCode>GBP</CharCode><Nominal>1</Nominal><Name>Фунт стерлингов Соединенного королевства</Name><Value>69,6402</Value></Valute><Valute ID="R01060"><NumCode>051</NumCode><CharCode>AMD</CharCode><Nominal>100</Nominal><Name>Армянских драмов</Name><Value>14,1184</Value></Valute><Valute ID="R01090B"><NumCode>933</NumCode><CharCode>BYN</CharCode><Nominal>1</Nominal><Name>Белорусский рубль</Name><Value>22,5531</Value></Valute><Valute ID="R01100"><NumCode>975</NumCode><CharCode>BGN</CharCode><Nominal>1</Nominal><Name>Болгарский лев</Name><Value>29,9860</Value></Valute><Valute ID="R01115"><NumCode>986</NumCode><CharCode>BRL</CharCode><Nominal>1</Nominal><Name>Бразильский реал</Name><Value>10,7903</Value></Valute><Valute ID="R01135"><NumCode>348</NumCode><CharCode>HUF</CharCode><Nominal>100</Nominal><Name>Венгерских форинтов</Name><Value>14,2437</Value></Valute><Valute ID="R01200"><NumCode>344</NumCode><CharCode>HKD</CharCode><Nominal>10</Nominal><Name>Гонконгских долларов</Name><Value>74,3451</Value></Valute><Valute ID="R01215"><NumCode>208</NumCode><CharCode>DKK</CharCode><Nominal>10</Nominal><Name>Датских крон</Name><Value>78,8095</Value></Valute><Valute ID="R01235"><NumCode>840</NumCode><CharCode>USD</CharCode><Nominal>1</Nominal><Name>Доллар США</Name><Value>58,2568</Value></Valute><Valute ID="R01239"><NumCode>978</NumCode><CharCode>EUR</CharCode><Nominal>1</Nominal><Name>Евро</Name><Value>58,3432</Value></Valute><Valute ID="R01270"><NumCode>356</NumCode><CharCode>INR</CharCode><Nominal>100</Nominal><Name>Индийских рупий</Name><Value>73,7209</Value></Valute><Valute ID="R01335"><NumCode>398</NumCode><CharCode>KZT</CharCode><Nominal>100</Nominal><Name>Казахстанских тенге</Name><Value>12,2411</Value></Valute><Valute ID="R01350"><NumCode>124</NumCode><CharCode>CAD</CharCode><Nominal>1</Nominal><Name>Канадский доллар</Name><Value>44,8958</Value></Valute><Valute ID="R01370"><NumCode>417</NumCode><CharCode>KGS</CharCode><Nominal>100</Nominal><Name>Киргизских сомов</Name><Value>71,8333</Value></Valute><Valute ID="R01375"><NumCode>156</NumCode><CharCode>CNY</CharCode><Nominal>10</Nominal><Name>Китайских юаней</Name><Value>86,3954</Value></Valute><Valute ID="R01500"><NumCode>498</NumCode><CharCode>MDL</CharCode><Nominal>10</Nominal><Name>Молдавских леев</Name><Value>30,1747</Value></Valute><Valute ID="R01535"><NumCode>578</NumCode><CharCode>NOK</CharCode><Nominal>10</Nominal><Name>Норвежских крон</Name><Value>56,8792</Value></Valute><Valute ID="R01565"><NumCode>985</NumCode><CharCode>PLN</CharCode><Nominal>1</Nominal><Name>Польский злотый</Name><Value>12,1073</Value></Valute><Valute ID="R01585F"><NumCode>946</NumCode><CharCode>RON</CharCode><Nominal>1</Nominal><Name>Румынский лей</Name><Value>11,8286</Value></Valute><Valute ID="R01589"><NumCode>960</NumCode><CharCode>XDR</CharCode><Nominal>1</Nominal><Name>СДР (специальные права заимствования)</Name><Value>76,4318</Value></Valute><Valute ID="R01625"><NumCode>702</NumCode><CharCode>SGD</CharCode><Nominal>1</Nominal><Name>Сингапурский доллар</Name><Value>41,7432</Value></Valute><Valute ID="R01670"><NumCode>972</NumCode><CharCode>TJS</CharCode><Nominal>10</Nominal><Name>Таджикских сомони</Name><Value>55,5424</Value></Valute><Valute ID="R01700J"><NumCode>949</NumCode><CharCode>TRY</CharCode><Nominal>10</Nominal><Name>Турецких лир</Name><Value>33,4675</Value></Valute><Valute ID="R01710A"><NumCode>934</NumCode><CharCode>TMT</CharCode><Nominal>1</Nominal><Name>Новый туркменский манат</Name><Value>16,6448</Value></Valute><Valute ID="R01717"><NumCode>860</NumCode><CharCode>UZS</CharCode><Nominal>10000</Nominal><Name>Узбекских сумов</Name><Value>53,2746</Value></Valute><Valute ID="R01720"><NumCode>980</NumCode><CharCode>UAH</CharCode><Nominal>10</Nominal><Name>Украинских гривен</Name><Value>19,7724</Value></Valute><Valute ID="R01760"><NumCode>203</NumCode><CharCode>CZK</CharCode><Nominal>10</Nominal><Name>Чешских крон</Name><Value>24,0294</Value></Valute><Valute ID="R01770"><NumCode>752</NumCode><CharCode>SEK</CharCode><Nominal>10</Nominal><Name>Шведских крон</Name><Value>55,0091</Value></Valute><Valute ID="R01775"><NumCode>756</NumCode><CharCode>CHF</CharCode><Nominal>1</Nominal><Name>Швейцарский франк</Name><Value>59,1860</Value></Valute><Valute ID="R01810"><NumCode>710</NumCode><CharCode>ZAR</CharCode><Nominal>10</Nominal><Name>Южноафриканских рэндов</Name><Value>34,1935</Value></Valute><Valute ID="R01815"><NumCode>410</NumCode><CharCode>KRW</CharCode><Nominal>1000</Nominal><Name>Вон Республики Корея</Name><Value>44,3997</Value></Valute><Valute ID="R01820"><NumCode>392</NumCode><CharCode>JPY</CharCode><Nominal>100</Nominal><Name>Японских иен</Name><Value>42,2151</Value></Valute></ValCurs>
2022-07-14 17:15:34,328 [DEBUG] - CbrApi:rate after: XRate(840=>643): 58.2568
2022-07-14 17:15:34,328 [INFO] - CbrApi:Finished update for: XRate(840=>643): 58.2568
2022-07-14 17:15:34,408 [INFO] - TestApi:Started update for: 840=>980
2022-07-14 17:15:34,409 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-14 17:15:34,412 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-14 17:15:34,412 [INFO] - TestApi:Finished update for: 840=>980
2022-07-14 17:15:56,442 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-14 17:15:56,442 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-14 17:15:57,248 [ERROR] - PrivatApi:Error during request sending
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f612e19d8e0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.privatbank.ua', port=443): Max retries exceeded with url: /p24api/pubinfo?exchange&json&coursid=11 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f612e19d8e0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 46, in _send_request
    response = self._send(method=method, url=url, headers=headers, data=data)
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 60, in _send
    return requests.request(method=method, url=url, headers=headers, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.privatbank.ua', port=443): Max retries exceeded with url: /p24api/pubinfo?exchange&json&coursid=11 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f612e19d8e0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)'))
2022-07-14 17:15:57,350 [INFO] - CbrApi:Started update for: XRate(840=>643): 1.0
2022-07-14 17:15:57,350 [DEBUG] - CbrApi:rate before: XRate(840=>643): 1.0
2022-07-14 17:15:58,790 [DEBUG] - CbrApi:response.encoding: windows-1251
2022-07-14 17:15:58,791 [DEBUG] - CbrApi:response.text: <?xml version="1.0" encoding="windows-1251"?><ValCurs Date="15.07.2022" name="Foreign Currency Market"><Valute ID="R01010"><NumCode>036</NumCode><CharCode>AUD</CharCode><Nominal>1</Nominal><Name>Австралийский доллар</Name><Value>39,3641</Value></Valute><Valute ID="R01020A"><NumCode>944</NumCode><CharCode>AZN</CharCode><Nominal>1</Nominal><Name>Азербайджанский манат</Name><Value>34,2687</Value></Valute><Valute ID="R01035"><NumCode>826</NumCode><CharCode>GBP</CharCode><Nominal>1</Nominal><Name>Фунт стерлингов Соединенного королевства</Name><Value>69,6402</Value></Valute><Valute ID="R01060"><NumCode>051</NumCode><CharCode>AMD</CharCode><Nominal>100</Nominal><Name>Армянских драмов</Name><Value>14,1184</Value></Valute><Valute ID="R01090B"><NumCode>933</NumCode><CharCode>BYN</CharCode><Nominal>1</Nominal><Name>Белорусский рубль</Name><Value>22,5531</Value></Valute><Valute ID="R01100"><NumCode>975</NumCode><CharCode>BGN</CharCode><Nominal>1</Nominal><Name>Болгарский лев</Name><Value>29,9860</Value></Valute><Valute ID="R01115"><NumCode>986</NumCode><CharCode>BRL</CharCode><Nominal>1</Nominal><Name>Бразильский реал</Name><Value>10,7903</Value></Valute><Valute ID="R01135"><NumCode>348</NumCode><CharCode>HUF</CharCode><Nominal>100</Nominal><Name>Венгерских форинтов</Name><Value>14,2437</Value></Valute><Valute ID="R01200"><NumCode>344</NumCode><CharCode>HKD</CharCode><Nominal>10</Nominal><Name>Гонконгских долларов</Name><Value>74,3451</Value></Valute><Valute ID="R01215"><NumCode>208</NumCode><CharCode>DKK</CharCode><Nominal>10</Nominal><Name>Датских крон</Name><Value>78,8095</Value></Valute><Valute ID="R01235"><NumCode>840</NumCode><CharCode>USD</CharCode><Nominal>1</Nominal><Name>Доллар США</Name><Value>58,2568</Value></Valute><Valute ID="R01239"><NumCode>978</NumCode><CharCode>EUR</CharCode><Nominal>1</Nominal><Name>Евро</Name><Value>58,3432</Value></Valute><Valute ID="R01270"><NumCode>356</NumCode><CharCode>INR</CharCode><Nominal>100</Nominal><Name>Индийских рупий</Name><Value>73,7209</Value></Valute><Valute ID="R01335"><NumCode>398</NumCode><CharCode>KZT</CharCode><Nominal>100</Nominal><Name>Казахстанских тенге</Name><Value>12,2411</Value></Valute><Valute ID="R01350"><NumCode>124</NumCode><CharCode>CAD</CharCode><Nominal>1</Nominal><Name>Канадский доллар</Name><Value>44,8958</Value></Valute><Valute ID="R01370"><NumCode>417</NumCode><CharCode>KGS</CharCode><Nominal>100</Nominal><Name>Киргизских сомов</Name><Value>71,8333</Value></Valute><Valute ID="R01375"><NumCode>156</NumCode><CharCode>CNY</CharCode><Nominal>10</Nominal><Name>Китайских юаней</Name><Value>86,3954</Value></Valute><Valute ID="R01500"><NumCode>498</NumCode><CharCode>MDL</CharCode><Nominal>10</Nominal><Name>Молдавских леев</Name><Value>30,1747</Value></Valute><Valute ID="R01535"><NumCode>578</NumCode><CharCode>NOK</CharCode><Nominal>10</Nominal><Name>Норвежских крон</Name><Value>56,8792</Value></Valute><Valute ID="R01565"><NumCode>985</NumCode><CharCode>PLN</CharCode><Nominal>1</Nominal><Name>Польский злотый</Name><Value>12,1073</Value></Valute><Valute ID="R01585F"><NumCode>946</NumCode><CharCode>RON</CharCode><Nominal>1</Nominal><Name>Румынский лей</Name><Value>11,8286</Value></Valute><Valute ID="R01589"><NumCode>960</NumCode><CharCode>XDR</CharCode><Nominal>1</Nominal><Name>СДР (специальные права заимствования)</Name><Value>76,4318</Value></Valute><Valute ID="R01625"><NumCode>702</NumCode><CharCode>SGD</CharCode><Nominal>1</Nominal><Name>Сингапурский доллар</Name><Value>41,7432</Value></Valute><Valute ID="R01670"><NumCode>972</NumCode><CharCode>TJS</CharCode><Nominal>10</Nominal><Name>Таджикских сомони</Name><Value>55,5424</Value></Valute><Valute ID="R01700J"><NumCode>949</NumCode><CharCode>TRY</CharCode><Nominal>10</Nominal><Name>Турецких лир</Name><Value>33,4675</Value></Valute><Valute ID="R01710A"><NumCode>934</NumCode><CharCode>TMT</CharCode><Nominal>1</Nominal><Name>Новый туркменский манат</Name><Value>16,6448</Value></Valute><Valute ID="R01717"><NumCode>860</NumCode><CharCode>UZS</CharCode><Nominal>10000</Nominal><Name>Узбекских сумов</Name><Value>53,2746</Value></Valute><Valute ID="R01720"><NumCode>980</NumCode><CharCode>UAH</CharCode><Nominal>10</Nominal><Name>Украинских гривен</Name><Value>19,7724</Value></Valute><Valute ID="R01760"><NumCode>203</NumCode><CharCode>CZK</CharCode><Nominal>10</Nominal><Name>Чешских крон</Name><Value>24,0294</Value></Valute><Valute ID="R01770"><NumCode>752</NumCode><CharCode>SEK</CharCode><Nominal>10</Nominal><Name>Шведских крон</Name><Value>55,0091</Value></Valute><Valute ID="R01775"><NumCode>756</NumCode><CharCode>CHF</CharCode><Nominal>1</Nominal><Name>Швейцарский франк</Name><Value>59,1860</Value></Valute><Valute ID="R01810"><NumCode>710</NumCode><CharCode>ZAR</CharCode><Nominal>10</Nominal><Name>Южноафриканских рэндов</Name><Value>34,1935</Value></Valute><Valute ID="R01815"><NumCode>410</NumCode><CharCode>KRW</CharCode><Nominal>1000</Nominal><Name>Вон Республики Корея</Name><Value>44,3997</Value></Valute><Valute ID="R01820"><NumCode>392</NumCode><CharCode>JPY</CharCode><Nominal>100</Nominal><Name>Японских иен</Name><Value>42,2151</Value></Valute></ValCurs>
2022-07-14 17:15:58,796 [DEBUG] - CbrApi:rate after: XRate(840=>643): 58.2568
2022-07-14 17:15:58,796 [INFO] - CbrApi:Finished update for: XRate(840=>643): 58.2568
2022-07-14 17:15:58,868 [INFO] - CryptonatorApi:Started update for: XRate(1000=>980): 1.0
2022-07-14 17:15:58,869 [DEBUG] - CryptonatorApi:rate before: XRate(1000=>980): 1.0
2022-07-14 17:15:59,684 [INFO] - PrivatApi:Started update for: XRate(1000=>840): 1.0
2022-07-14 17:15:59,684 [DEBUG] - PrivatApi:rate before: XRate(1000=>840): 1.0
2022-07-14 17:16:00,367 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'buy': '36.49630', 'sale': '36.49635'}, {'ccy': 'EUR', 'base_ccy': 'UAH', 'buy': '36.62990', 'sale': '36.63004'}, {'ccy': 'RUR', 'base_ccy': 'UAH', 'buy': '0.32000', 'sale': '0.35001'}, {'ccy': 'BTC', 'base_ccy': 'USD', 'buy': '18730.3162', 'sale': '20701.9284'}]
2022-07-14 17:16:00,371 [DEBUG] - PrivatApi:rate after: XRate(1000=>840): 20701.9284
2022-07-14 17:16:00,371 [INFO] - PrivatApi:Finished update for: XRate(1000=>840): 20701.9284
2022-07-14 17:16:00,432 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-14 17:16:00,432 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-14 17:16:00,438 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'sale': '30.0'}]
2022-07-14 17:16:00,442 [DEBUG] - PrivatApi:rate after: XRate(840=>980): 30.0
2022-07-14 17:16:00,442 [INFO] - PrivatApi:Finished update for: XRate(840=>980): 30.0
2022-07-14 17:16:00,518 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-14 17:16:00,518 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-14 17:16:01,297 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'buy': '36.49630', 'sale': '36.49635'}, {'ccy': 'EUR', 'base_ccy': 'UAH', 'buy': '36.62990', 'sale': '36.63004'}, {'ccy': 'RUR', 'base_ccy': 'UAH', 'buy': '0.32000', 'sale': '0.35001'}, {'ccy': 'BTC', 'base_ccy': 'USD', 'buy': '18730.3162', 'sale': '20701.9284'}]
2022-07-14 17:16:01,302 [DEBUG] - PrivatApi:rate after: XRate(840=>980): 36.49635
2022-07-14 17:16:01,302 [INFO] - PrivatApi:Finished update for: XRate(840=>980): 36.49635
2022-07-15 13:07:38,418 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-15 13:07:38,418 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-15 13:07:38,894 [ERROR] - PrivatApi:Error during request sending
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f794ddf58b0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.privatbank.ua', port=443): Max retries exceeded with url: /p24api/pubinfo?exchange&json&coursid=11 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f794ddf58b0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 46, in _send_request
    response = self._send(method=method, url=url, headers=headers, data=data)
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 60, in _send
    return requests.request(method=method, url=url, headers=headers, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.privatbank.ua', port=443): Max retries exceeded with url: /p24api/pubinfo?exchange&json&coursid=11 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f794ddf58b0>, 'Connection to api.privatbank.ua timed out. (connect timeout=0.001)'))
2022-07-15 13:07:38,976 [INFO] - CbrApi:Started update for: XRate(840=>643): 1.0
2022-07-15 13:07:38,976 [DEBUG] - CbrApi:rate before: XRate(840=>643): 1.0
2022-07-15 13:07:39,535 [DEBUG] - CbrApi:response.encoding: windows-1251
2022-07-15 13:07:39,536 [DEBUG] - CbrApi:response.text: <?xml version="1.0" encoding="windows-1251"?><ValCurs Date="15.07.2022" name="Foreign Currency Market"><Valute ID="R01010"><NumCode>036</NumCode><CharCode>AUD</CharCode><Nominal>1</Nominal><Name>Австралийский доллар</Name><Value>39,3641</Value></Valute><Valute ID="R01020A"><NumCode>944</NumCode><CharCode>AZN</CharCode><Nominal>1</Nominal><Name>Азербайджанский манат</Name><Value>34,2687</Value></Valute><Valute ID="R01035"><NumCode>826</NumCode><CharCode>GBP</CharCode><Nominal>1</Nominal><Name>Фунт стерлингов Соединенного королевства</Name><Value>69,6402</Value></Valute><Valute ID="R01060"><NumCode>051</NumCode><CharCode>AMD</CharCode><Nominal>100</Nominal><Name>Армянских драмов</Name><Value>14,1184</Value></Valute><Valute ID="R01090B"><NumCode>933</NumCode><CharCode>BYN</CharCode><Nominal>1</Nominal><Name>Белорусский рубль</Name><Value>22,5531</Value></Valute><Valute ID="R01100"><NumCode>975</NumCode><CharCode>BGN</CharCode><Nominal>1</Nominal><Name>Болгарский лев</Name><Value>29,9860</Value></Valute><Valute ID="R01115"><NumCode>986</NumCode><CharCode>BRL</CharCode><Nominal>1</Nominal><Name>Бразильский реал</Name><Value>10,7903</Value></Valute><Valute ID="R01135"><NumCode>348</NumCode><CharCode>HUF</CharCode><Nominal>100</Nominal><Name>Венгерских форинтов</Name><Value>14,2437</Value></Valute><Valute ID="R01200"><NumCode>344</NumCode><CharCode>HKD</CharCode><Nominal>10</Nominal><Name>Гонконгских долларов</Name><Value>74,3451</Value></Valute><Valute ID="R01215"><NumCode>208</NumCode><CharCode>DKK</CharCode><Nominal>10</Nominal><Name>Датских крон</Name><Value>78,8095</Value></Valute><Valute ID="R01235"><NumCode>840</NumCode><CharCode>USD</CharCode><Nominal>1</Nominal><Name>Доллар США</Name><Value>58,2568</Value></Valute><Valute ID="R01239"><NumCode>978</NumCode><CharCode>EUR</CharCode><Nominal>1</Nominal><Name>Евро</Name><Value>58,3432</Value></Valute><Valute ID="R01270"><NumCode>356</NumCode><CharCode>INR</CharCode><Nominal>100</Nominal><Name>Индийских рупий</Name><Value>73,7209</Value></Valute><Valute ID="R01335"><NumCode>398</NumCode><CharCode>KZT</CharCode><Nominal>100</Nominal><Name>Казахстанских тенге</Name><Value>12,2411</Value></Valute><Valute ID="R01350"><NumCode>124</NumCode><CharCode>CAD</CharCode><Nominal>1</Nominal><Name>Канадский доллар</Name><Value>44,8958</Value></Valute><Valute ID="R01370"><NumCode>417</NumCode><CharCode>KGS</CharCode><Nominal>100</Nominal><Name>Киргизских сомов</Name><Value>71,8333</Value></Valute><Valute ID="R01375"><NumCode>156</NumCode><CharCode>CNY</CharCode><Nominal>10</Nominal><Name>Китайских юаней</Name><Value>86,3954</Value></Valute><Valute ID="R01500"><NumCode>498</NumCode><CharCode>MDL</CharCode><Nominal>10</Nominal><Name>Молдавских леев</Name><Value>30,1747</Value></Valute><Valute ID="R01535"><NumCode>578</NumCode><CharCode>NOK</CharCode><Nominal>10</Nominal><Name>Норвежских крон</Name><Value>56,8792</Value></Valute><Valute ID="R01565"><NumCode>985</NumCode><CharCode>PLN</CharCode><Nominal>1</Nominal><Name>Польский злотый</Name><Value>12,1073</Value></Valute><Valute ID="R01585F"><NumCode>946</NumCode><CharCode>RON</CharCode><Nominal>1</Nominal><Name>Румынский лей</Name><Value>11,8286</Value></Valute><Valute ID="R01589"><NumCode>960</NumCode><CharCode>XDR</CharCode><Nominal>1</Nominal><Name>СДР (специальные права заимствования)</Name><Value>76,4318</Value></Valute><Valute ID="R01625"><NumCode>702</NumCode><CharCode>SGD</CharCode><Nominal>1</Nominal><Name>Сингапурский доллар</Name><Value>41,7432</Value></Valute><Valute ID="R01670"><NumCode>972</NumCode><CharCode>TJS</CharCode><Nominal>10</Nominal><Name>Таджикских сомони</Name><Value>55,5424</Value></Valute><Valute ID="R01700J"><NumCode>949</NumCode><CharCode>TRY</CharCode><Nominal>10</Nominal><Name>Турецких лир</Name><Value>33,4675</Value></Valute><Valute ID="R01710A"><NumCode>934</NumCode><CharCode>TMT</CharCode><Nominal>1</Nominal><Name>Новый туркменский манат</Name><Value>16,6448</Value></Valute><Valute ID="R01717"><NumCode>860</NumCode><CharCode>UZS</CharCode><Nominal>10000</Nominal><Name>Узбекских сумов</Name><Value>53,2746</Value></Valute><Valute ID="R01720"><NumCode>980</NumCode><CharCode>UAH</CharCode><Nominal>10</Nominal><Name>Украинских гривен</Name><Value>19,7724</Value></Valute><Valute ID="R01760"><NumCode>203</NumCode><CharCode>CZK</CharCode><Nominal>10</Nominal><Name>Чешских крон</Name><Value>24,0294</Value></Valute><Valute ID="R01770"><NumCode>752</NumCode><CharCode>SEK</CharCode><Nominal>10</Nominal><Name>Шведских крон</Name><Value>55,0091</Value></Valute><Valute ID="R01775"><NumCode>756</NumCode><CharCode>CHF</CharCode><Nominal>1</Nominal><Name>Швейцарский франк</Name><Value>59,1860</Value></Valute><Valute ID="R01810"><NumCode>710</NumCode><CharCode>ZAR</CharCode><Nominal>10</Nominal><Name>Южноафриканских рэндов</Name><Value>34,1935</Value></Valute><Valute ID="R01815"><NumCode>410</NumCode><CharCode>KRW</CharCode><Nominal>1000</Nominal><Name>Вон Республики Корея</Name><Value>44,3997</Value></Valute><Valute ID="R01820"><NumCode>392</NumCode><CharCode>JPY</CharCode><Nominal>100</Nominal><Name>Японских иен</Name><Value>42,2151</Value></Valute></ValCurs>
2022-07-15 13:07:39,541 [DEBUG] - CbrApi:rate after: XRate(840=>643): 58.2568
2022-07-15 13:07:39,541 [INFO] - CbrApi:Finished update for: XRate(840=>643): 58.2568
2022-07-15 13:07:39,612 [INFO] - CryptonatorApi:Started update for: XRate(1000=>980): 1.0
2022-07-15 13:07:39,612 [DEBUG] - CryptonatorApi:rate before: XRate(1000=>980): 1.0
2022-07-15 13:07:40,520 [INFO] - PrivatApi:Started update for: XRate(1000=>840): 1.0
2022-07-15 13:07:40,520 [DEBUG] - PrivatApi:rate before: XRate(1000=>840): 1.0
2022-07-15 13:07:41,562 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'buy': '36.36350', 'sale': '36.36364'}, {'ccy': 'EUR', 'base_ccy': 'UAH', 'buy': '36.36350', 'sale': '36.36364'}, {'ccy': 'RUR', 'base_ccy': 'UAH', 'buy': '0.32000', 'sale': '0.35001'}, {'ccy': 'BTC', 'base_ccy': 'USD', 'buy': '19838.6005', 'sale': '21926.8743'}]
2022-07-15 13:07:41,567 [DEBUG] - PrivatApi:rate after: XRate(1000=>840): 21926.8743
2022-07-15 13:07:41,567 [INFO] - PrivatApi:Finished update for: XRate(1000=>840): 21926.8743
2022-07-15 13:07:41,634 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-15 13:07:41,634 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-15 13:07:41,639 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'sale': '30.0'}]
2022-07-15 13:07:41,643 [DEBUG] - PrivatApi:rate after: XRate(840=>980): 30.0
2022-07-15 13:07:41,643 [INFO] - PrivatApi:Finished update for: XRate(840=>980): 30.0
2022-07-15 13:07:41,705 [INFO] - PrivatApi:Started update for: XRate(840=>980): 1.0
2022-07-15 13:07:41,705 [DEBUG] - PrivatApi:rate before: XRate(840=>980): 1.0
2022-07-15 13:07:42,585 [DEBUG] - PrivatApi:Privat response: [{'ccy': 'USD', 'base_ccy': 'UAH', 'buy': '36.36350', 'sale': '36.36364'}, {'ccy': 'EUR', 'base_ccy': 'UAH', 'buy': '36.36350', 'sale': '36.36364'}, {'ccy': 'RUR', 'base_ccy': 'UAH', 'buy': '0.32000', 'sale': '0.35001'}, {'ccy': 'BTC', 'base_ccy': 'USD', 'buy': '19838.6005', 'sale': '21926.8743'}]
2022-07-15 13:07:42,589 [DEBUG] - PrivatApi:rate after: XRate(840=>980): 36.36364
2022-07-15 13:07:42,589 [INFO] - PrivatApi:Finished update for: XRate(840=>980): 36.36364
2022-07-15 21:28:37,779 [INFO] - TestApi:Started update for: 840=>980
2022-07-15 21:28:37,781 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-15 21:28:37,786 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-15 21:28:37,786 [INFO] - TestApi:Finished update for: 840=>980
2022-07-15 21:28:54,751 [INFO] - CbrApi:Started update for: XRate(840=>643): 1.0
2022-07-15 21:28:54,751 [DEBUG] - CbrApi:rate before: XRate(840=>643): 1.0
2022-07-15 21:29:04,761 [ERROR] - CbrApi:Error during request sending
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd79ef62b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.cbr.ru', port=80): Max retries exceeded with url: /scripts/XML_daily.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd79ef62b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 46, in _send_request
    response = self._send(method=method, url=url, headers=headers, data=data)
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 60, in _send
    return requests.request(method=method, url=url, headers=headers, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cbr.ru', port=80): Max retries exceeded with url: /scripts/XML_daily.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd79ef62b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-07-15 21:29:04,836 [INFO] - TestApi:Started update for: 840=>980
2022-07-15 21:29:04,836 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-15 21:29:04,840 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-15 21:29:04,840 [INFO] - TestApi:Finished update for: 840=>980
2022-07-15 21:33:13,208 [INFO] - CbrApi:Started update for: XRate(840=>643): 1.0
2022-07-15 21:33:13,208 [DEBUG] - CbrApi:rate before: XRate(840=>643): 1.0
2022-07-15 21:33:23,222 [ERROR] - CbrApi:Error during request sending
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fca14618b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.cbr.ru', port=80): Max retries exceeded with url: /scripts/XML_daily.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca14618b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 46, in _send_request
    response = self._send(method=method, url=url, headers=headers, data=data)
  File "/home/andrii/MyProjects/Flask/Practice Flask/Урок 7/lesson 7/api/__init__.py", line 60, in _send
    return requests.request(method=method, url=url, headers=headers, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cbr.ru', port=80): Max retries exceeded with url: /scripts/XML_daily.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca14618b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-07-15 21:33:23,293 [INFO] - TestApi:Started update for: 840=>980
2022-07-15 21:33:23,294 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-15 21:33:23,298 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-15 21:33:23,298 [INFO] - TestApi:Finished update for: 840=>980
2022-07-15 21:35:56,083 [INFO] - TestApi:Started update for: 840=>980
2022-07-15 21:35:56,084 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-15 21:35:56,088 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-15 21:35:56,089 [INFO] - TestApi:Finished update for: 840=>980
2022-07-15 21:37:41,029 [INFO] - TestApi:Started update for: 840=>980
2022-07-15 21:37:41,030 [DEBUG] - TestApi:rate before: XRate(840=>980): 1.0
2022-07-15 21:37:41,035 [DEBUG] - TestApi:rate after: XRate(840=>980): 1.01
2022-07-15 21:37:41,035 [INFO] - TestApi:Finished update for: 840=>980
